nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  "@react-aria/overlays@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/dialog@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/contextualhelp@*":
    peerDependencies:
      react-dom: "*"
  "react-transition-group@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/dnd@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/icon@*":
    peerDependencies:
      react-dom: "*"
      "@react-spectrum/provider": "*"
  "@spectrum-icons/illustrations@*":
    peerDependencies:
      react-dom: "*"
      "@react-spectrum/provider": "*"
